version: "3"
services:
  app-server:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: poetry run python3 manage.py runserver 0.0.0.0:8023
    ports:
      - "8023:8023"
    networks:
      - payment-network
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
