version: "3"
services:
  app-server:
    build:
      context: .
      dockerfile: dockerfile.prod
    working_dir: /app
    command: sh ./setup.sh
    ports:
      - "8023:8023"
    networks:
      - payment-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
      - PGPORT=5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - payment-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Nginx:/etc/nginx/conf.d
    depends_on:
      - app-server
    networks:
      - payment-network
networks:
  payment-network:
    driver: bridge
