# Generated by Django 4.2.4 on 2023-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_omise_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
