# Generated by Django 4.2.4 on 2023-11-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_user_customer_omise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
