# Generated by Django 4.2.4 on 2023-11-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_code_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Statement',
        ),
    ]
