# Generated by Django 4.2.4 on 2023-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_payment_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
